package au.com.imed.portal.referrer.referrerportal.rest.consts;

import java.util.HashMap;
import java.util.Map;

public class OrderStatusConst {
  public static final String STATUS_GROUP_PENDING = "pending";
  public static final String STATUS_GROUP_STARTED = "started";
  public static final String STATUS_GROUP_IMAGES_AVAILABLE = "images available";
  public static final String STATUS_GROUP_COMPLETE = "complete";
  
  public static final Map<String, String[]> STATUS_GROUP_MAP;
  public static final Map<String, String> GROUP_STATUS_MAP;
  static{
    STATUS_GROUP_MAP = new HashMap<>(3);
    STATUS_GROUP_MAP.put(STATUS_GROUP_PENDING, new String [] {"REQUESTED", "APPOINTMENT_BOOKED", "APPOINTMENT_CONFIRMED"});
    STATUS_GROUP_MAP.put(STATUS_GROUP_STARTED, new String [] {"ARRIVED", "SCAN_STARTED", "SCAN_COMPLETED", "IMAGES_INCOMPLETE"});
    STATUS_GROUP_MAP.put(STATUS_GROUP_IMAGES_AVAILABLE, new String [] {"IMAGES_VERIFIED", "INTERPRETATION_STARTED", "INTERPRETATION_HELD", "INTERPRETATION_COMPLETE", "UNAUTHORISED_REPORT"});
    STATUS_GROUP_MAP.put(STATUS_GROUP_COMPLETE, new String [] {"COMPLETE"});
    
    GROUP_STATUS_MAP = new HashMap<>(20);
    GROUP_STATUS_MAP.put("REQUESTED", STATUS_GROUP_PENDING);
    GROUP_STATUS_MAP.put("APPOINTMENT_BOOKED", STATUS_GROUP_PENDING);
    GROUP_STATUS_MAP.put("APPOINTMENT_CONFIRMED", STATUS_GROUP_PENDING);
    GROUP_STATUS_MAP.put("ARRIVED", STATUS_GROUP_STARTED);
    GROUP_STATUS_MAP.put("SCAN_STARTED", STATUS_GROUP_STARTED);
    GROUP_STATUS_MAP.put("SCAN_COMPLETED", STATUS_GROUP_STARTED);
    GROUP_STATUS_MAP.put("IMAGES_INCOMPLETE", STATUS_GROUP_STARTED);
    GROUP_STATUS_MAP.put("IMAGES_VERIFIED", STATUS_GROUP_IMAGES_AVAILABLE);
    GROUP_STATUS_MAP.put("INTERPRETATION_STARTED", STATUS_GROUP_IMAGES_AVAILABLE);
    GROUP_STATUS_MAP.put("INTERPRETATION_HELD", STATUS_GROUP_IMAGES_AVAILABLE);
    GROUP_STATUS_MAP.put("INTERPRETATION_COMPLETE", STATUS_GROUP_IMAGES_AVAILABLE);
    GROUP_STATUS_MAP.put("UNAUTHORISED_REPORT", STATUS_GROUP_IMAGES_AVAILABLE);
    GROUP_STATUS_MAP.put("COMPLETE", STATUS_GROUP_COMPLETE);
    GROUP_STATUS_MAP.put("DISCONTINUED", "DISCONTINUED");   // special treatment 
    GROUP_STATUS_MAP.put("CANCELLED", "CANCELLED");   // special treatment 
  }
}
